### PR TITLE
Add support for detecting url

### PR DESCRIPTION
**Pull request by zjffun**
Like https://github.com/dependents/node-detective-postcss add an `uri` option.

### CODE REVIEW

**Comment by XhmikosR** [comment]
@zjffun please see https://github.com/dependents/node-detective-sass and the main branch here and adapt the changes.

**Comment by zjffun** [comment]
> @zjffun please see https://github.com/dependents/node-detective-sass and the main branch here and adapt the changes.

OK, I'll update this weekend.

**Comment by zjffun** [comment]
@XhmikosR I updated this PR according to the main branch of https://github.com/dependents/node-detective-sass .

**Comment by XhmikosR** [comment]
Perfect, thanks!

**Review by XhmikosR — APPROVED** [review]

**Pull request merged**
